[package]
name = "seq_io"
version = "0.1.0"
authors = ["<markschl19@gmail.com>"]
description = "Performant FASTA and FASTQ readers"
license = "MIT"
repository = "https://github.com/markschl/seq_io"
documentation = ""
readme = "README.md"
keywords = ["bio", "fasta", "fastq", "parser"]
exclude = [
    "bench_results/bench.txt",
    "bench_results/bench_fasta.png",
    "bench_results/bench_fastq.png",
]

[dependencies]
memchr = "^1"
buf_redux = "^0.6"
scoped_threadpool ="^0.1"
crossbeam = "^0.2"

[dev-dependencies]
bio = "^0.14"
lazy_static = "^0.2"
fastq = "*"

[profile.bench]
lto = true
