[package]
name = "seq_io"
version = "0.1.0"
authors = ["<markschl19@gmail.com>"]
description = "Performant FASTA and FASTQ readers"
license = "MIT"
repository = "https://github.com/markschl/seq_io"
documentation = "https://docs.rs/seq_io"
readme = "README.md"
keywords = ["bio", "fasta", "fastq", "parser"]
exclude = [
    "bench_results/*",
]

[dependencies]
memchr = "^1"
buf_redux = "^0.6"
scoped_threadpool ="^0.1"
crossbeam = "^0.2"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
bio = "^0.14"
fastq = "^0.5"

[profile.bench]
lto = true
