[package]
name = "seq_io"
version = "0.2.6"
authors = ["<markschl19@gmail.com>"]
description = "Fast FASTA and FASTQ readers"
license = "MIT"
repository = "https://github.com/markschl/seq_io"
documentation = "https://docs.rs/seq_io"
readme = "README.md"
keywords = ["bio", "fasta", "fastq", "parser"]
exclude = [
    "bench_results/*",
]

[dependencies]
memchr = "2.0"
buf_redux = "0.7"
scoped_threadpool ="0.1"
crossbeam = "0.4"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
bio = "0.22"
fastq = "0.6"
matches = "0.1"
lazy_static = "1.1"
rand = "0.5"
criterion = { version = "0.2", default_features = false }

[profile.bench]
lto = true

[[bench]]
name = "fasta"
harness = false

[[bench]]
name = "fastq"
harness = false
